- name: install and run nginx
  hosts: web
  become: yes  # -b (become root user)
  tasks:
    - name: install nginx
      ansible.builtin.package:  # this can make ansible heterogeneous---on any platform we can run#ansible.builtin.dnf ----- homogeneous (only on redhat enterprise we can run this package)
        name: nginx
        state: present # present = install; absent = remove
    - name: start the nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes