- name : install and run nginx
  hosts : web
  become : yes  # -b (become root user)
  tasks :
    - name : install nginx
      ansible.builtin.package:  # this can make ansible heterogeneous---on any platform we can run
        #ansible.builtin.dnf ----- homogeneous (only on redhat enterprise we can run this package)
        name : install nginx
        state: present # present = install; absent = remove
    - name : start nginx
      ansible.builtin.service
        name : start the service
        state : started