- name: variables
  hosts: local
  connection: local
  vars: #PLAY-level variables & Global variables
    COURSE: "Devops with AWS"
    DURATION: 120HRS
    TRAINER: SIVAREDDY
  tasks:
  - name: print variables
    vars: 
      COURSE: ANSIBLE #task-level variables, accessible only with in the task. Task variables can override play level variables
    ansible.builtin.debug:
      msg: " I have joined {{ COURSE }} course, and it's duration is {{ DURATION }}. Trainer is {{ TRAINER }}"
  - name: print variables 
    ansible.builtin.debug: 
      msg: " I have joined {{ COURSE }} course, and it's duration is {{ DURATION }}. Trainer is {{ TRAINER }}"