- name: using variables file
  hosts: local
  connection: local
  vars_files:  
  - variables.yaml
  tasks: 
  - name: print variables file information
    ansible.builtin.debug:
      msg: "I have joined {{ COURSE }} course, it's duration is {{ DURATION }}. Trainer is {{ TRAINER }}."
  - name: print variables
    vars: 
      COURSE: ANSIBLE #task-level variables, accessible only with in the task. Task variables can override play level variables
    ansible.builtin.debug:
      msg: " I have joined {{ COURSE }} course, and it's duration is {{ DURATION }}. Trainer is {{ TRAINER }}"