- name: using variables file
  hosts: local
  connection: local
  vars_files:  
  - variables.yaml
  tasks: 
  - name: print variables file information
    ansible.builtin.debug:
      msg: "I have joined {{ COURSE }} course, it's duration is {{ DURATION }}. Trainer is {{ TRAINER }}."