- name: using variables inventory
  hosts: local
  connection: local
  tasks: 
  - name: print variables from inventory 
    ansible.builtin.debug:
      msg: "I have joined {{ COURSE }} course, it's duration is {{ DURATION }}. Trainer is {{ TRAINER }}."
  