- name: print inventory variables
  hosts: local
  connection: local
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "I have joined {{ COURSE }} course, it's duration is {{ DURATION }}. Trainer is {{ TRAINER }}."