- name: packages
  hosts: web
  become: yes
  tasks:
  - name: install and removing packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'git', state: 'present'}
    - { name: 'gcc', state: 'absemt'}
    - { name: 'mysql', state: 'absent'}
    - { name: 'zip', state: 'present'}
  
