- name: shell and command module 
  hosts: local
  connection: local
  tasks:
  - name: execute shell module
    #ansible.builtin.command: ls -ltr > /tmp/output.txt ----will not work
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: execute command module
    ansible.builtin.command: ls -ltr
  register: command_result  #to store output

  - name: print the stored output
    ansible.builtin.debug:
      msg: "{{ command_result }}"