- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-05cf3f3858247f740
    sg_id: sg-0e3e5c6f4e37ec583
    ami_id: ami-09c813fb71547fc4f
    instance_type: t2.micro
    instances:
    - mysql
    - backend
    - frontend

  tasks:
  - name: Install python libraries
    ansible.builtin.pip:
     name: "{{ item }}"
     executable: pip3.9
    loop:
     - botocore
     - boto3

  - name: create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: print the stored output
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"

  - name: print private addresses
    ansible.builtin.debug:
      msg: "{{item.instances[0].item}}: {{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"

    